# Generated by Django 5.1 on 2024-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Химические_показатели', 'Химические_показатели'), ('Определение_удельной_активности', 'Определение_удельной_активности'), ('Токсикологические_исследования', 'Токсикологические_исследования'), ('Гидробиологические_исследования', 'Гидробиологические_исследования')], max_length=100, verbose_name='Категория')),
                ('category', models.CharField(choices=[('Морская вода', 'Морская вода'), ('Донные отложения', 'Донные отложения'), ('Грунты', 'Грунты'), ('Почва', 'Почва')], max_length=100, verbose_name='Тип показателя')),
                ('value', models.IntegerField(default=0, verbose_name='Значение')),
                ('name_of_indicators', models.TextField(verbose_name='Наименование показателя')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Адрес местонахождения Заказчика')),
                ('name_official', models.CharField(default='Директор Жигульский В.А', max_length=255, verbose_name='Должность')),
                ('contract', models.CharField(max_length=255, verbose_name='Договор')),
                ('name_of_the_object', models.TextField(verbose_name='Наименование объекта')),
                ('location_object', models.TextField(verbose_name='Место расположения объекта')),
                ('the_presence_of_harmful_factors', models.BooleanField(default=False, verbose_name='Наличие вредных производственных факторов')),
                ('the_purpose_of_the_research', models.CharField(max_length=255, verbose_name='Цель проведения исследований')),
                ('indicators', models.ManyToManyField(to='application.postvalue', verbose_name='Показатели')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-contract'],
            },
        ),
    ]
